USE [master]
GO

/****** Object:  Database [catuc_st]    Script Date: 12/6/2025 8:11:47 PM ******/
CREATE DATABASE [catuc_st]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'catuc_st', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\catuc_st.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'catuc_st_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\catuc_st_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [catuc_st].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [catuc_st] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [catuc_st] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [catuc_st] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [catuc_st] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [catuc_st] SET ARITHABORT OFF 
GO

ALTER DATABASE [catuc_st] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [catuc_st] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [catuc_st] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [catuc_st] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [catuc_st] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [catuc_st] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [catuc_st] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [catuc_st] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [catuc_st] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [catuc_st] SET  DISABLE_BROKER 
GO

ALTER DATABASE [catuc_st] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [catuc_st] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [catuc_st] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [catuc_st] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [catuc_st] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [catuc_st] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [catuc_st] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [catuc_st] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [catuc_st] SET  MULTI_USER 
GO

ALTER DATABASE [catuc_st] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [catuc_st] SET DB_CHAINING OFF 
GO

ALTER DATABASE [catuc_st] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [catuc_st] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [catuc_st] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [catuc_st] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [catuc_st] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [catuc_st] SET QUERY_STORE = ON
GO

ALTER DATABASE [catuc_st] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [catuc_st] SET  READ_WRITE 
GO


